export const CONSTS = {
    LOGIN:{
        MAIN_TITLE: "VacationApp",
        SUB_TITLE: "Log In",
        NO_ACCOUNT: "Don’t have an account?",
        SIGNUP: "Signup"
    },
    SIGNUP: {
    MAIN_TITLE: "VacationApp",
    SUB_TITLE: "Register",
    FIRST_NAME_LABEL: "first name",
    LAST_NAME_LABEL: "last name",
    EMAIL_LABEL: "email",
    PASSWORD_LABEL: "password",
    BUTTON: "Register",
    ALREADY_MEMBER: "already a member?",
    LOGIN: "Login",
  },
    CREATE_VACATIONS: {
    TITLE: "Add Vacation",
    COUNTRY_LABEL: "country",
    COUNTRY_PLACEHOLDER: "Select Country",
    DESCRIPTION_LABEL: "description",
    DESCRIPTION_PLACEHOLDER: "Enter description",
    START_LABEL: "start on",
    END_LABEL: "end on",
    PRICE_LABEL: "price",
    PRICE_PLACEHOLDER: "0.00",
    CURRENCY_SYMBOL: "$",
    COVER_LABEL: "cover image",
    SELECT_IMAGE: "Select Image",
    ADD_BUTTON: "Add Vacation",
    CANCEL_BUTTON: "Cancel",
    COUNTRY_OPTIONS: ["Italy", "Spain", "France"],
  },
     EDIT_VACATIONS: {
    TITLE: "Edit Vacation",
    COUNTRY_LABEL: "country",
    COUNTRY_PLACEHOLDER: "Select Country",
    DESCRIPTION_LABEL: "description",
    START_LABEL: "start on",
    END_LABEL: "end on",
    PRICE_LABEL: "price",
    CURRENCY_SYMBOL: "$",
    COVER_LABEL: "cover image",
    CHANGE_IMAGE: "Change Image",
    SELECT_IMAGE: "Select Image",
    UPDATE_BUTTON: "Update",
    CANCEL_BUTTON: "Cancel",
    COUNTRY_OPTIONS: ["Rhodes", "Italy", "Spain", "France"],
  },
    HOMEPAGE:{

    },
    NAVBAR: {
    LOGO: "VacationApp",
    HOME: "Home",
    LOGIN: "Login",
    SIGNUP: "Signup",
    TOGGLE_ARIA: "Toggle menu",
  },
}